#
#	Vseobecny config
#

terminaly:
    - '<!DOCTYPE'
    - '['
    - ']>'
    - '<!ELEMENT'
    - 'EMPTY'
    - '>'
    - '>'
	
    - 'ANY'	
    - '(#PCDATA)'
    - '(' 
    - ')'
    - '|'
    - ','
    - '?'
    - '*'
    - '+'
    - '<!ATTLIST'
    - 'CDATA'
    - 'NMTOKEN'
    - 'IDREF'
    - '#REQUIRED'
    - '#IMPLIED'
    - '"'
    - '_'
    - ':'
    - '.'
    - '-'
    - 'A'
    - 'B'
    - 'C'
    - 'D'
    - 'E'
    - 'F'
    - 'G'
    - 'H'
    - 'I'
    - 'J'
    - 'K'
    - 'L'
    - 'M'
    - 'N'
    - 'O'
    - 'Q'
    - 'R'
    - 'S'
    - 'T'
    - 'U'
    - 'V'
    - 'Z'
    - 'X'
    - 'Y'
    - 'Z'
    - '1'
    - '2'
    - '3'	
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
	
#    - 'E'

empty_symbol: E

gramatika:
    - S -> '<!DOCTYPE' name '[' dtddocument ']>'
    - dtddocument -> declaration next                           # aby sme ich mohli nagenerovat nekonecne vela
    - next -> declaration next | E                              # raz treba aj skoncit  :) 
    - declaration -> elemdec | attrdec                          # deklarujeme element alebo atribut
    - elemdec -> '<!ELEMENT' name innerelem '>'
    - innerelem -> 'EMPTY' | 'ANY' | '(#PCDATA)' | '(' elemchild ')' count
    - elemchild -> item nextitem
    - nextitem -> '|' choice | ',' sequence | E                 # elementy mozeme mat v takomto tvare (a|b|c) alebo (a,b,c)
    - choice -> item ch
    - ch -> '|' choice | E                                      # nagenerovanie elementov oddelenych |
    - sequence -> item seq
    - seq -> ',' sequence | E                                   # nagenerovanie elementov oddelenych ciarkami
    - item -> name count
    - count -> '?' | '*' | '+' | E                              # pocetnost elementu
    - attrdec -> '<!ATTLIST' name specification '>'
    - specification -> name attrtype default specification | E  # neviem preco to takto je napisane v tom zadani...
                                                                # v ATTLISTE moze ist za sebou viac tychto definicii?
                                                                # ja by som tam dal max 1 cize bez tej pravej rekurzie
    - attrtype -> 'CDATA' | 'NMTOKEN' | 'IDREF'                 # typy atributov
    - default -> '#REQUIRED' | '#IMPLIED' | fix '"' word nextword '"'
    - fix -> '#FIXED' | E                                       # vraj FIXED nemusi byt ?
    - nextword -> word | E
    - name -> letter namechar | '_' namechar | ':' namechar
    - namechar -> letter namechar | digit namechar | '.' namechar | '-' namechar | '_' namechar | ':' namechar | E
    - word -> char | char word
    - char -> letter | digit                                    # vraj tu maju byt este nejake znaky ale to neviem ake  :) 
    - letter -> 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'Z' | 'X' | 'Y'
    - digit -> '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'


